### ISSUE TITLE
Problem with the visual query builder

### ISSUE THREAD

**Issue by cbettemb** [askomics/askomics#204]
Hello Askoteam,

I can finally use the docker installation of AskOmics. I tried on Linux and Windows, and I encountered different issues on both. This post is about Linux, using the last available version of AskOmics with docker.

Virtuoso and AskOmics are running well and the integration part is working fine, but nodes are not displayed in the query builder. After picking a starting node, the visualisation interface opens but no node appears in the grey box. The content of the console is:

```
-+-+- displayNavbar -+-+- askomics.js:6:1770
{} askomics.js:1:28036
========== start session ForceLayoutManager ============== askomics.js:5:622
D3.JS version:3.5.17 askomics.js:5:696
TypeError: Object.values is not a function
```

I'm using Firefox 45.3.0 (and I can't update it).
I'm still behind a ntlm proxy, but I don't think this is the problem this time since the integration is working well. Any idea of what can cause it?

Thanks,
Charles

**Comment by cbettemb** [comment]
The problem was related to the Firefox version. It's working fine with Firefox 56.0.2.
